@BCVPDotNet8_HostAddress = http://localhost:5283

GET {{BCVPDotNet8_HostAddress}}/weatherforecast/Get
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ1c2VyMTIzIiwianRpIjoiNGRlMWIyMDEtNTkwMy00OWIwLWE5MmEtMjIzMWUyMjk3MDlhIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiU3VwZXJBZG1pbiIsImV4cCI6MTc1MjA0NjQ2MSwiaXNzIjoiWmxpbS5Db3JlIiwiYXVkIjoiemxpbSJ9.2HwPfw0uf0gJJn8pi3--r0pr107pVj-5HttjU8NC2oU
###
