@BCVPDotNet8_HostAddress = http://localhost:5283

GET {{BCVPDotNet8_HostAddress}}/weatherforecast/Get
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ1c2VyMTIzIiwianRpIjoiMzgwMzg1OWQtOWQzZS00ODM2LTkxNzUtNTI4NTI1MWEwNzAwIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiVXNlciIsImV4cCI6MTc1MjAzNzUzMiwiaXNzIjoiWmxpbS5Db3JlIiwiYXVkIjoiemxpbSJ9.FdAqPO3hIxJq7loJlT24KKmL8Vp_YH37rZ8fIiShDX8
###
